nmap <Leader>dt <Plug>(go-def-tab)
nmap <leader>r <Plug>(go-run)
nmap <leader>b <Plug>(go-build)
nmap <leader>t <Plug>(go-test)
nmap <leader>co <Plug>(go-coverage)
nmap <Leader>gd <Plug>(go-doc-vertical)
nmap <leader>r <Plug>(go-rename)
" nmap <Leader>s <Plug>(go-implements)
